AWSTemplateFormatVersion: 2010-09-09
Description: To Create EC2instance from CloudFormation Stack
Resources:
  EC2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami- 
      InstanceType: t2.micro
      KeyName: keyname
      SecurityGroupIds: 
         - !Ref WebAppSecurityGroup
      UserData: 
        Fn::Base64: |
         #!/bin/bash -xe
         yum update -y # good practice to update existing packages
         yum install -y httpd # install web server 
         systemctl start httpd
         systemctl enable httpd
         echo "Hello vishnu" > /var/www/html/index.html   
  WebAppSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
    GroupName: dev
    GroupDescription: "Allow HTTP,HTTPS&SSH Inbound and Outbound Traffic"
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0



            
